### ISSUE TITLE
some request ;)

### ISSUE THREAD

**Issue by solor** [ckaotik/ckaosMilitia#2]
mission expires time for every mission in garrison report window and mission list window, currently it only shows for rare mission.
"Mission complete" alerts show in chat instead of a pop-up window, but keep the sound.
bigger enemy threats in mission list window, they look really small.

![222333](https://cloud.githubusercontent.com/assets/156806/6485369/3f0cd7b6-c2be-11e4-92e1-4ac1b7ce4b45.jpg)

**Comment by ckaotik** [comment]
Hey solor :) I hope you realize that this screenshot is not of ckaosMilitia...?

For your requests:
1. Mission expiry: I can add this to the mission tooltip, sure! See commit 73b27a2
2. Alerts: There are already some addons that suppress these popups (e.g. LeatrixPlus, Mission Hush). I'll have to think about wheather or not I want to add this to the addon.
3. Bigger threat icons: Probably not happening anytime soon - take a loot at [Nephilist: Garrison](http://www.curse.com/addons/wow/nephilist-garrison) or any of the other addons out there.

**Comment by solor** [comment]
thanks for reply, screenshot took from Nephilist: Garrison, I used it for a long time that's why i like big threat icon, but it looks like abandoned ;(
anyway, thanks for your hard work, I really enjoy this addon.
